# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sdk-reforge 1.11.2 ruby lib

Gem::Specification.new do |s|
  s.name = "sdk-reforge".freeze
  s.version = "1.11.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeff Dwyer".freeze]
  s.date = "2025-10-24"
  s.description = "Feature Flags, Live Config as a service".freeze
  s.email = "jeff.dwyer@reforge.com.cloud".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".DS_Store",
    ".envrc.sample",
    ".github/CODEOWNERS",
    ".github/pull_request_template.md",
    ".github/workflows/push_gem.yml",
    ".github/workflows/ruby.yml",
    ".gitmodules",
    ".rubocop.yml",
    ".tool-versions",
    "CHANGELOG.md",
    "CODEOWNERS",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "compile_protos.sh",
    "dev/allocation_stats",
    "dev/benchmark",
    "dev/console",
    "dev/script_setup.rb",
    "lib/prefab_pb.rb",
    "lib/reforge/caching_http_connection.rb",
    "lib/reforge/client.rb",
    "lib/reforge/config_client.rb",
    "lib/reforge/config_client_presenter.rb",
    "lib/reforge/config_loader.rb",
    "lib/reforge/config_resolver.rb",
    "lib/reforge/config_value_unwrapper.rb",
    "lib/reforge/config_value_wrapper.rb",
    "lib/reforge/context.rb",
    "lib/reforge/context_shape.rb",
    "lib/reforge/context_shape_aggregator.rb",
    "lib/reforge/criteria_evaluator.rb",
    "lib/reforge/duration.rb",
    "lib/reforge/encryption.rb",
    "lib/reforge/error.rb",
    "lib/reforge/errors/env_var_parse_error.rb",
    "lib/reforge/errors/initialization_timeout_error.rb",
    "lib/reforge/errors/invalid_sdk_key_error.rb",
    "lib/reforge/errors/missing_default_error.rb",
    "lib/reforge/errors/missing_env_var_error.rb",
    "lib/reforge/errors/uninitialized_error.rb",
    "lib/reforge/evaluation.rb",
    "lib/reforge/evaluation_summary_aggregator.rb",
    "lib/reforge/example_contexts_aggregator.rb",
    "lib/reforge/exponential_backoff.rb",
    "lib/reforge/feature_flag_client.rb",
    "lib/reforge/fixed_size_hash.rb",
    "lib/reforge/http_connection.rb",
    "lib/reforge/internal_logger.rb",
    "lib/reforge/javascript_stub.rb",
    "lib/reforge/local_config_parser.rb",
    "lib/reforge/log_level.rb",
    "lib/reforge/log_level_client.rb",
    "lib/reforge/murmer3.rb",
    "lib/reforge/options.rb",
    "lib/reforge/periodic_sync.rb",
    "lib/reforge/rate_limit_cache.rb",
    "lib/reforge/reforge.rb",
    "lib/reforge/resolved_config_presenter.rb",
    "lib/reforge/semver.rb",
    "lib/reforge/sse_config_client.rb",
    "lib/reforge/time_helpers.rb",
    "lib/reforge/weighted_value_resolver.rb",
    "lib/reforge/yaml_config_parser.rb",
    "lib/sdk-reforge.rb",
    "sdk-reforge.gemspec",
    "test/fixtures/datafile.json",
    "test/integration_test.rb",
    "test/integration_test_helpers.rb",
    "test/support/common_helpers.rb",
    "test/support/mock_base_client.rb",
    "test/support/mock_config_client.rb",
    "test/support/mock_config_loader.rb",
    "test/test_caching_http_connection.rb",
    "test/test_client.rb",
    "test/test_config_client.rb",
    "test/test_config_loader.rb",
    "test/test_config_resolver.rb",
    "test/test_config_value_unwrapper.rb",
    "test/test_config_value_wrapper.rb",
    "test/test_context.rb",
    "test/test_context_shape.rb",
    "test/test_context_shape_aggregator.rb",
    "test/test_criteria_evaluator.rb",
    "test/test_duration.rb",
    "test/test_encryption.rb",
    "test/test_evaluation_summary_aggregator.rb",
    "test/test_example_contexts_aggregator.rb",
    "test/test_exponential_backoff.rb",
    "test/test_feature_flag_client.rb",
    "test/test_fixed_size_hash.rb",
    "test/test_helper.rb",
    "test/test_integration.rb",
    "test/test_internal_logger.rb",
    "test/test_javascript_stub.rb",
    "test/test_local_config_parser.rb",
    "test/test_log_level_client.rb",
    "test/test_logger_initialization.rb",
    "test/test_options.rb",
    "test/test_prefab.rb",
    "test/test_rate_limit_cache.rb",
    "test/test_semver.rb",
    "test/test_sse_config_client.rb",
    "test/test_weighted_value_resolver.rb"
  ]
  s.homepage = "http://github.com/ReforgeHQ/sdk-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.4.19".freeze
  s.summary = "Reforge Launch Ruby Infrastructure".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<concurrent-ruby>.freeze, ["~> 1.0", ">= 1.0.5"])
  s.add_runtime_dependency(%q<faraday>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<googleapis-common-protos-types>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<google-protobuf>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<ld-eventsource>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<uuid>.freeze, [">= 0"])
  s.add_runtime_dependency(%q<activesupport>.freeze, [">= 4"])
  s.add_development_dependency(%q<allocation_stats>.freeze, [">= 0"])
  s.add_development_dependency(%q<benchmark-ips>.freeze, [">= 0"])
  s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9"])
  s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
  s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
end

