# frozen_string_literal: true

module Reforge
  NO_DEFAULT_PROVIDED = :no_default_provided
  VERSION = File.read(File.dirname(__FILE__) + '/../VERSION').strip
end

require 'semantic_logger'
require 'reforge/internal_logger'
require 'concurrent/atomics'
require 'concurrent'
require 'faraday'
require 'openssl'
require 'ld-eventsource'
require 'prefab_pb'
require 'reforge/time_helpers'
require 'reforge/error'
require 'reforge/duration'
require 'reforge/evaluation'
require 'reforge/encryption'
require 'reforge/exponential_backoff'
require 'reforge/errors/initialization_timeout_error'
require 'reforge/errors/invalid_sdk_key_error'
require 'reforge/errors/missing_default_error'
require 'reforge/errors/env_var_parse_error'
require 'reforge/errors/missing_env_var_error'
require 'reforge/errors/uninitialized_error'
require 'reforge/options'
require 'reforge/rate_limit_cache'
require 'reforge/context_shape_aggregator'
require 'reforge/example_contexts_aggregator'
require 'reforge/evaluation_summary_aggregator'
require 'reforge/weighted_value_resolver'
require 'reforge/config_value_wrapper'
require 'reforge/config_value_unwrapper'
require 'reforge/criteria_evaluator'
require 'reforge/config_loader'
require 'reforge/context_shape'
require 'reforge/local_config_parser'
require 'reforge/yaml_config_parser'
require 'reforge/resolved_config_presenter'
require 'reforge/config_resolver'
require 'reforge/http_connection'
require 'reforge/context'
require 'active_support/deprecation'
require 'active_support'
require 'reforge/sse_config_client'
require 'reforge/client'
require 'reforge/config_client_presenter'
require 'reforge/config_client'
require 'reforge/feature_flag_client'
require 'reforge/log_level'
require 'reforge/log_level_client'
require 'reforge/reforge'
require 'reforge/murmer3'
require 'reforge/javascript_stub'
require 'reforge/semver'
require 'reforge/fixed_size_hash'
require 'reforge/caching_http_connection'